# Generated by Django 5.2.11 on 2026-02-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип')),
                ('icon', models.ImageField(upload_to='icon', verbose_name='Иконка')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('locate', models.URLField(verbose_name='Ссылка на карту')),
            ],
        ),
    ]
